
  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_l2jd7Ac7dHwqw1wYn0MoVycIYOrrh2w',
    appId: '1:754059636258:web:717bcf729c32881b88a47b',
    messagingSenderId: '754059636258',
    projectId: 'auto-pulse-pro',
    authDomain: 'auto-pulse-pro.firebaseapp.com',
    storageBucket: 'auto-pulse-pro.appspot.com',
    measurementId: 'G-J4FB3G3T8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpEkC-WIt8p6mobYqSlrH8rGhTL-z16U',
    appId: '1:754059636258:android:4b414d647b47b84088a47b',
    messagingSenderId: '754059636258',
    projectId: 'auto-pulse-pro',
    storageBucket: 'auto-pulse-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_aah_mvODd9aVu1hc-XOSC2_Wgl-7QcQ',
    appId: '1:754059636258:ios:1acaf2a365a218a388a47b',
    messagingSenderId: '754059636258',
    projectId: 'auto-pulse-pro',
    storageBucket: 'auto-pulse-pro.appspot.com',
    iosBundleId: 'com.autoPulsePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_aah_mvODd9aVu1hc-XOSC2_Wgl-7QcQ',
    appId: '1:754059636258:ios:1acaf2a365a218a388a47b',
    messagingSenderId: '754059636258',
    projectId: 'auto-pulse-pro',
    storageBucket: 'auto-pulse-pro.appspot.com',
    iosBundleId: 'com.autoPulsePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_l2jd7Ac7dHwqw1wYn0MoVycIYOrrh2w',
    appId: '1:754059636258:web:082638e6e19eb91888a47b',
    messagingSenderId: '754059636258',
    projectId: 'auto-pulse-pro',
    authDomain: 'auto-pulse-pro.firebaseapp.com',
    storageBucket: 'auto-pulse-pro.appspot.com',
    measurementId: 'G-WSRQQJ08L5',
  );

}